### ISSUE TITLE
RUSTFLAGS aren't read from `~/.cargo/config.toml`, needs documentation

### ISSUE THREAD

**Issue by xangelix** [ronnychevalier/cargo-multivers#11] opened 2024-06-18 15:03 UTC
Noticed with `--cfg reqwest_unstable` for http3 support in the reqwest crate under either `[target.x86_64-unknown-linux-gnu]` or `[build]`. But this works fine when directly appended to the env/shell variable.
Considering multivers as separate to this config might be fine, but wasn't what I was expecting.

On that note-- is multivers not compatible with any RUSTFLAGS. For example, is using the [`mold`](https://github.com/rui314/mold) linker, i.e. `-C linker=clang -C link-arg=-fuse-ld=/usr/bin/mold` safe with multivers?

**Comment by ronnychevalier** [comment] 2024-06-19 20:47
Both `RUSTFLAGS` and `$CARGO_HOME/config.toml` are supported. The reason is that `cargo multivers` is calling `cargo build`, so `cargo build` will read this file. Same for `RUSTFLAGS` since `cargo` is calling `rustc`. These variables/files are supported for each build of your project **and** for the build of the runner.
I just tested that `config.toml` is parsed when using `cargo multivers` and it works.

So if you use `mold` it should work like any other project.

Can you give me a precise example so that I can try to reproduce the behavior you describe? 

The only environment variable that is not propagated to the **runner** is [`CARGO_UNSTABLE_BUILD_STD`](https://github.com/ronnychevalier/cargo-multivers/blob/830ccc0f7b85e935a0e6b260ce52a94b5cbd0a63/src/runner.rs#L90) to avoid confusion in case one forgets to use `panic_abort` (this is not perfect but was a reasonable fix for #7). The variable, however, is still propagated to each build of your project.

**Comment by ronnychevalier** [comment] 2024-07-10 18:25
I'm gonna close this issue since I'm not able to reproduce it.
Feel free to reopen it if you can provide a sample to reproduce it.

**Closed by ronnychevalier** 2024-07-10 18:25 UTC
